#' @include generics.R
#' @include qboneassay.R
#' @include utils.R
#' @importFrom data.table fread
#' @useDynLib Qbone
#'
NULL

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Class definitions ----
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

## The Qbone Class ----
#' The Qbone Class
#'
#' The Qbone object is a representation of data analysis using Quantile
#' Functional Regression using Quantlets (doi: 10.1080/01621459.2019.1609969)
#' for R.
#'
#' @slot assays A list of assays for this project.
#' structure like assay name
#'                  ├── sample list
#'                  │        ├── sample 1
#'                  │        ├── sample 2
#'                  ...      ...
#'                  │        └── sample x
#'                  └── assay information
#' @slot meta.data Meta information regarding each sample.
#' @slot active.assay Name of the active, or default, assay; settable using
#' \code{\link{DefaultAssay}}
#' @slot active.ident The active identity for this Qbone object;
#' settable using \code{\link{Idents}}
#' @slot graphs list of \code{\link{Graph}} objects                                 || double check
#' @slot images A list of image objects                                             || double check
#' @slot project.name Name of the project
#' @slot misc A list of miscellaneous information                                   || double check
#' @slot version Version of Seurat this object was built under
#' @slot commands A list of logged commands run on this \code{Seurat} object        || double check
#' @slot tools A list of miscellaneous data generated by other tools, should be     || double check
#' filled by developers only using \code{\link{Tool}<-}
#'

Qbone <- setClass(
  Class = 'Qbone',
  slots = c(
    assays = 'list',
    meta.data = 'data.frame',
    active.assay = 'character',
    active.ident = 'factor',
    graphs = 'list',
    images = 'list',
    project.name = 'character',
    misc = 'list',
    version = 'package_version', # function OK but infinite list under this slot.
                                 # list(packageVersion()) ended up the same.
    commands = 'list',
    tools = 'list'
  ),
  prototype = c(
    assays = list(),
    active.assay = NA_character_,
    active.ident = factor(),
    graphs = list(),
    images = list(),
    project.name = "Qbone",
    misc = list(),
    # version = packageVersion(pkg = "Qbone"),
    commands = list(),
    tools = list()
  )
)

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Functions ----
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# R-defined generics ----
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

"[[.Qbone" <- function(x, i, ..., drop = FALSE) {
  x <- updateSlots(object = x)
  if (missing(x = i)) {
    i <- colnames(x = slot(object = x, name = 'meta.data'))
  }
  if (length(x = i) == 0) {
    return(data.frame(row.names = colnames(x = x)))
  } else if (length(x = i) > 1 || any(i %in% colnames(x = slot(object = x, name = 'meta.data')))) {
    if (any(!i %in% colnames(x = slot(object = x, name = 'meta.data')))) {
      warning(
        "Cannot find the following bits of meta data: ",
        paste0(
          i[!i %in% colnames(x = slot(object = x, name = 'meta.data'))],
          collapse = ', '
        )
      )
    }
    i <- i[i %in% colnames(x = slot(object = x, name = 'meta.data'))]
    data.return <- slot(object = x, name = 'meta.data')[, i, drop = FALSE, ...]
    if (drop) {
      data.return <- unlist(x = data.return, use.names = FALSE)
      names(x = data.return) <- rep.int(x = colnames(x = x), times = length(x = i))
    }
  } else {
    slot.use <- unlist(x = lapply(
      X = c('assays', 'graphs', 'images'),
      FUN = function(s) {
        if (any(i %in% names(x = slot(object = x, name = s)))) {
          return(s)
        }
        return(NULL)
      }
    ))
    if (is.null(x = slot.use)) {
      stop("Cannot find '", i, "' in this Qbone object", call. = FALSE)
    }
    data.return <- slot(object = x, name = slot.use)[[i]]
  }
  return(data.return)
}
