# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Faster Matrix Multiplication
#'
#' Faster matrix multiplication using C++ Eigen.
#' A * B
#'
#' @param A,B Matrices.
#' @rdname eigenmatrix
#' @export
eigenmm <- function(A, B) {
    .Call(`_Qbone_eigenmm`, A, B)
}

#' Faster Matrix Transpose
#'
#' Faster matrix multiplication using C++ Eigen.
#' t(A)
#'
#' @param A Matrices.
#' @rdname eigenmatrix
#' @export
eigenmt <- function(A) {
    .Call(`_Qbone_eigenmt`, A)
}

#' Faster Matrix Transpose (Eigen::Map)
#'
#' Faster matrix multiplication using C++ Eigen::Map
#' t(A)
#'
#' @param A Matrices.
#' @rdname eigenmatrix
#' @export
eigenmapmt <- function(A) {
    .Call(`_Qbone_eigenmapmt`, A)
}

#' Faster Matrix Multiplication (Eigen::Map)
#'
#' Faster matrix multiplication using C++ Eigen::Map.
#' A * B
#'
#' @param A,B Matrices.
#' @rdname eigenmatrix
#' @export
eigenmapmm <- function(A, B) {
    .Call(`_Qbone_eigenmapmm`, A, B)
}

#' Faster Matrix Multiplication (Eigen::Map)
#'
#' Faster matrix multiplication using C++ Eigen::Map.
#' A * t(B)
#'
#' @param A,B Matrices.
#' @rdname eigenmatrix
#' @export
eigenmapmmt <- function(A, B) {
    .Call(`_Qbone_eigenmapmmt`, A, B)
}

#' Faster Matrix Multiplication (Eigen::Map)
#'
#' Faster matrix multiplication using C++ Eigen::Map.
#' t(A) * B
#'
#' @param A,B Matrices.
#' @rdname eigenmatrix
#' @export
eigenmapmtm <- function(A, B) {
    .Call(`_Qbone_eigenmapmtm`, A, B)
}

