# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenMatMult <- function(A, B) {
    .Call('_Qbone_eigenMatMult', PACKAGE = 'Qbone', A, B)
}

eigenMatMulttrans <- function(A, B) {
    .Call('_Qbone_eigenMatMulttrans', PACKAGE = 'Qbone', A, B)
}

eigenMapMatMult <- function(A, B) {
    .Call('_Qbone_eigenMapMatMult', PACKAGE = 'Qbone', A, B)
}

eigenMapMatMulttrans <- function(A, B) {
    .Call('_Qbone_eigenMapMatMulttrans', PACKAGE = 'Qbone', A, B)
}

eigentransMapMatMult <- function(A, B) {
    .Call('_Qbone_eigentransMapMatMult', PACKAGE = 'Qbone', A, B)
}

