# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenmm <- function(A, B) {
    .Call('_Qbone_eigenmm', PACKAGE = 'Qbone', A, B)
}

eigenmt <- function(A) {
    .Call('_Qbone_eigenmt', PACKAGE = 'Qbone', A)
}

eigenmapmt <- function(A) {
    .Call('_Qbone_eigenmapmt', PACKAGE = 'Qbone', A)
}

eigenmapmm <- function(A, B) {
    .Call('_Qbone_eigenmapmm', PACKAGE = 'Qbone', A, B)
}

eigenmapmmt <- function(A, B) {
    .Call('_Qbone_eigenmapmmt', PACKAGE = 'Qbone', A, B)
}

eigenmapmtm <- function(A, B) {
    .Call('_Qbone_eigenmapmtm', PACKAGE = 'Qbone', A, B)
}

